src/CI/BandkadaBundle/Entity/Album.php
<?php

namespace CI\BandkadaBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContextInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Album
 *
 * @ORM\Table(name="album")
 * @ORM\Entity(repositoryClass="CI\BandkadaBundle\Entity\AlbumRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Assert\Callback(methods={"process"})
 */
class Album extends BaseEntity
{
	/**
	 * @ORM\Column(name="name", type="string", length=36)
	 * @Assert\Length(min=1, max=36)
	 * @Assert\Type(type="string")
	 * @Assert\NotBlank(message="Name is required.")
	 */
	protected $name;
	
	/**
	 * @var date
	 *
	 * @ORM\Column(name="event_date", type="date")
	 * @Assert\NotBlank(message="Event date is required.")
	 * @Assert\Date()
	 */
	private $eventDate;
	
	/**
	 * @ORM\Column(name="description", type="text")
	 * @Assert\Type(type="string")
	 * @Assert\NotBlank(message="Description is required.")
	 */
	protected $description;
	
	/**
	 * @ORM\OneToMany(targetEntity="Media", mappedBy="album", cascade={"persist", "remove"})
	 * @ORM\OrderBy({"id" = "ASC"})
	 * @Assert\Count(min="1", minMessage="You must add at least one media.")
	 * @Assert\Valid
	 */
	protected $media;
	
	/**
	 * @ORM\Column(name="filename", type="string", length=255)
	 */
	private	$filename;
	
	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Type(type="string")
	 * @Assert\Length(max=255)
	 */
	private	$path;
	
	/**
	 * @Assert\File(maxSize="300M")
	 */
	private $file;
	
	private $temp;
	
	private $changeImage;
	
	/**
	 * Constructor
	 */
	public function __construct()
	{
		$this->media = new \Doctrine\Common\Collections\ArrayCollection();
	}
	
	public function getAbsolutePath()
	{
		return null === $this->path ? null : $this->getUploadRootDir() . '/' . $this->path;
	}
	
	public function getWebPath()
	{
		return null === $this->path ? null : $this->getUploadDir() . '/' . $this->path;
	}
	
	protected function getUploadRootDir()
	{
		return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}
	
	protected function getUploadDir()
	{
		return 'uploads/albums';
	}
	
	/**
	 * Sets changeImage
	 *
	 * @param boolean $deleteImage
	 */
	public function setChangeImage($changeImage)
	{
		$this->changeImage = $changeImage;
	
		return $this;
	}
	
	public function getChangeImage()
	{
		return $this->changeImage;
	}

    /**
     * Set name
     *
     * @param string $name
     * @return Album
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set eventDate
     *
     * @param \DateTime $eventDate
     * @return Album
     */
    public function setEventDate($eventDate)
    {
        $this->eventDate = $eventDate;
    
        return $this;
    }

    /**
     * Get eventDate
     *
     * @return \DateTime 
     */
    public function getEventDate()
    {
        return $this->eventDate;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Album
     */
    public function setDescription($description)
    {
        $this->description = $description;
    
        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Add media
     *
     * @param \CI\BandkadaBundle\Entity\Media $media
     * @return Album
     */
    public function addMedium(\CI\BandkadaBundle\Entity\Media $media)
    {
    	$media->setAlbum($this);
        $this->media[] = $media;
    
        return $this;
    }

    /**
     * Remove media
     *
     * @param \CI\BandkadaBundle\Entity\Media $media
     */
    public function removeMedium(\CI\BandkadaBundle\Entity\Media $media)
    {
        $this->media->removeElement($media);
    }

    /**
     * Get media
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMedia()
    {
        return $this->media;
    }
    
    /**
     * Set filename
     *
     * @param string $filename
     * @return Album
     */
    public function setFilename($filename)
    {
    	$this->filename = $filename;
    
    	return $this;
    }
    
    /**
     * Get filename
     *
     * @return string
     */
    public function getFilename()
    {
    	return $this->filename;
    }
    
    /**
     * Set path
     *
     * @param string $path
     * @return Album
     */
    public function setPath($path)
    {
    	$this->path = $path;
    
    	return $this;
    }
    
    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
    	return $this->path;
    }
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
    	$this->file = $file;
    	// check if we have an old image path
    	if (is_file($this->getAbsolutePath())) {
    		// store the old name to delete after the update
    		$this->temp = $this->getAbsolutePath();
    	} else {
    		$this->path = 'initial';
    	}
    }
    
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
    	return $this->file;
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
    	if (null !== $this->getFile()) {
    		// do whatever you want to generate a unique name
    		$this->setFilename($this->getFile()->getClientOriginalName());
    		$filename = sha1(uniqid(mt_rand(), true));
    		$this->path = $filename . '.' . $this->getFile()->guessExtension();
    	}
    }
    
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
    	if (null === $this->getFile()) {
    		return;
    	}
    	 
    	$this->getFile()->move($this->getUploadRootDir(), $this->path);
    	 
    	// check if we have an old image
    	if (isset($this->temp)) {
    		// delete the old image
    		unlink($this->temp);
    		// clear the temp image path
    		$this->temp = null;
    	}
    	 
    	$this->file = null;
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
    	$file = $this->getAbsolutePath();
    	if ($file) {
    		unlink($file);
    	}
    }
    
    public function process(ExecutionContextInterface $context)
    {
    	if (!empty($this->file)) {
    		if ($this->checkExtension($this->file->guessExtension()) === false) {
    			$context->addViolationAt("file", "Invalid image format uploaded.");
    		} else {
    			// this updates the file incase no other fields are updated.
    			$this->setUpdatedAt(new \DateTime('now'));
    		}
    	} else {
    		if (!$this->getId() || ($this->getId() && $this->getChangeImage())) {
    			$context->addViolationAt('file', 'Album cover is required.');
    		}
    	}
    }
    
    private function checkExtension($extension) 
    {
    	$allowedExtensions = array(
    		'jpeg', 'png', 'jpg'
    	);
    	return in_array($extension, $allowedExtensions);
    }
    
    public function getPaginatedMedia($countPerPage)
    {
    	if (empty($countPerPage)) {
    		$countPerPage = $this->getMedia()->count();
    	}
    	
    	$count = 1;
    	$pageNo = 0;
    	$pages = array();
    	
    	foreach($this->getMedia() as $media) {
    		if ($count % $countPerPage === 1) {
    			$pageNo++;
    		}
    		
    		$pages[$pageNo][] = $media;
    		$count++;
    	}
    	
    	return $pages;
    }
}

src/CI/BandkadaBundle/Form/Type/AlbumType.php
<?php

namespace CI\BandkadaBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AlbumType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
		->add('name')
		->add('eventDate', 'date', array(
			'label'    => 'Event Date',
			'widget'   => 'single_text',
			'format'   => 'MM/dd/y',
			'required' => true,
			'attr'	   => array(
				'widget_col' => 5,
				'datepicker' => true,
				'input_group' => array('append' => 'calendar')
			)
		))
		->add('description', 'textarea', array(
			'attr' => array(
				'rows' => 5
			)
		))
		->add('media', 'collection', array(
			'type' => new MediaType(),
			'allow_add'=> true,
			'allow_delete'=> true,
			'by_reference' => false,
			'error_bubbling' => false
		))
		->add('file', 'file', array(
			'label' => 'Album Cover',
			'required' => true,
			'attr' => array(
				'class' => 'file-input'
			)
		))
		->add('changeImage', 'hidden', array(
			'attr' => array('class' => 'change-image'),
		))
		->add('save', 'submit', array(
			'label' => 'Save',
			'attr' => array(
				'class' => 'btn btn-primary submit-button',
				'data-loading-text' => "Saving..."
			)
		))
		;
	}
	
	/**
	 * @param OptionsResolverInterface $resolver
	 */
	public function setDefaultOptions(OptionsResolverInterface $resolver)
	{
		$resolver->setDefaults(array(
			'data_class' => 'CI\BandkadaBundle\Entity\Album'
		));
	}
	
	/**
	 * @return string
	 */
	public function getName()
	{
		return 'ci_bandkadabundle_album';
	}
}

src/CI/BandkadaBundle/Controller/Admin/AlbumController.php
<?php

namespace CI\BandkadaBundle\Controller\Admin;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

/**
 * Album controller.
 *
 * @Route("/album")
 */
class AlbumController extends BaseController
{
	const LINK_SHOW = 'album_show';
	
	public function getModel()
	{
		return $this->get('ci.album.model');
	}
	
    /**
     * Lists all Album.
     *
     * @Route("/", name="album")
     * @Method("GET")
     */
    public function indexAction(Request $request) 
    {
    	$model = $this->getModel();
    	$form = $model->getFilterFormType();
    	
    	if ($form->handleRequest($request)->isSubmitted()) {
    		if ($form->isValid()) {
    			$params = $form->getData();
    			$qb = $model->getIndex($params);
    		} else {
    			$this->get('session')->getFlashBag()->add('danger', 'Please try again.');
    		}
    	}
    	
    	if (!isset($qb)) {
    		$qb = $model->getIndex();
    	}
    	
    	$paginator = $this->get('knp_paginator');
    	$pagination = $paginator->paginate(
    		$qb,
    		$this->get('request')->query->get('page', 1),
    		$this->container->getParameter('pagination_limit_per_page')
    	);
    	
    	return $this->render('CIBandkadaBundle:Album:index.html.twig', array(
    		'pagination' => isset($pagination) ? $pagination : null,
    		'search_form' => $form->createView()
    	));
    }
    
    /**
     * Creates a new Album entity.
     *
     * @Route("/", name="album_create")
     * @Method("POST")
     */
    public function createAction(Request $request)
    {
    	$model = $this->getModel();
    	$entity = $model->getNewEntity();
    	$form = $model->getFormType($entity);
    
    	if ($form->handleRequest($request)->isSubmitted()) {
    		if ($form->isValid()) {
    			try {
    				$model->saveEntity($form, $entity);
    				$this->get('session')->getFlashBag()->add('success', $model->getMessages('create'));
    				return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
    			} catch (\Exception $e) {
    				$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
    			}
    		} else {
    			$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
    		}
    	}
    
    	return $this->render('CIBandkadaBundle:Album:new.html.twig', array(
    		'entity'    => $entity,
    		'form' => $form->createView()
    	));
    }
    
    /**
     * Displays a form to create a new Album entity.
     *
     * @Route("/new", name="album_new")
     * @Method("GET")
     */
    public function newAction()
    {
    	$model = $this->getModel();
    	$entity = $model->getNewEntity();
    	$form = $model->getFormType($entity);
    
    	return $this->render('CIBandkadaBundle:Album:new.html.twig', array(
    		'entity'    => $entity,
    		'form' => $form->createView()
    	));
    }

    /**
     * Finds and displays a Album entity.
     *
     * @Route("/{id}/show", requirements={"id"="\d+"}, name="album_show")
     * @Method("GET")
     */
    public function showAction($id)
    {
    	$model = $this->getModel();
    	$entity = $model->findExistingEntity($id);
    	
    	return $this->render('CIBandkadaBundle:Album:show.html.twig', array('entity' => $entity));
    }

    /**
     * Displays a form to edit an existing Album entity.
     *
     * @Route("/{id}/edit", requirements={"id"="\d+"}, name="album_edit")
     * @Method("GET")
     */
    public function editAction(Request $request, $id)
    {
    	$model = $this->getModel();
    	$entity = $model->findExistingEntity($id);
    	$editForm = $model->getFormType($entity);
    	
    	
    	return $this->render('CIBandkadaBundle:Album:edit.html.twig', array(
    		'entity'    => $entity,
    		'edit_form' => $editForm->createView()
    	));
    }

    /**
     * Edits an existing Band entity.
     *
     * @Route("/{id}", requirements={"id"="\d+"}, name="album_update")
     * @Method("PUT")
     */
    public function updateAction(Request $request, $id)
    {
    	$model = $this->getModel();
    	$entity = $model->findExistingEntity($id);
    	$model->storeOriginalItems($entity);
    	$editForm = $model->getFormType($entity);
    	
    	if ($editForm->handleRequest($request)->isSubmitted()) {
    		if ($editForm->isValid()) {
    			try {
    				$model->saveEntity($editForm, $entity);
    				$this->get('session')->getFlashBag()->add('success', $model->getMessages('update'));
    				return $this->redirect($this->generateUrl(self::LINK_SHOW, array('id' => $entity->getId())));
    			} catch (\Exception $e) {
    				$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
    			}
    		} else {
    			$this->get('session')->getFlashBag()->add('danger', 'Please fill in the correct values.');
    		}
    	}
    	
    	return $this->render('CIBandkadaBundle:Album:edit.html.twig', array(
    		'entity'    => $entity,
    		'edit_form' => $editForm->createView()
    	));
    }
    
    /**
	 * Creates a delete form.
	 *
	 * @Route("/confirm-delete/{id}", requirements={"id"="\d+"}, name="album_confirm_delete")
	 * @Method("GET")
	 * @Template("CIBandkadaBundle:Misc:delete.html.twig")
	 */
	public function confirmDeleteAction(Request $request, $id)
	{
		$model = $this->getModel();
		$entity = $model->findExistingEntity($id);
		$deleteForm = $this->createDeleteForm($id);
			
		return array(
			'entity' => $entity,
			'delete_form' => $deleteForm->createView(),
			'params' => $model->getDeleteParams($entity)
		);
	}
	
	/**
	 * Deletes an Album entity.
	 *
	 * @Route("/{id}", requirements={"id"="\d+"}, name="album_delete")
	 * @Method("DELETE")
	 */
	public function deleteAction(Request $request, $id)
	{
		$model = $this->getModel();
		$form = $this->createDeleteForm($id);
		
		if ($form->handleRequest($request)->isSubmitted()) {
			if ($form->isValid()) {
				try {
					$model->deleteEntity($id);
					$this->get('session')->getFlashBag()->add('success', $model->getMessages('delete'));
				} catch (\Exception $e) {
					$this->get('session')->getFlashBag()->add('danger', $e->getMessage());
				}
			} else {
				$this->get('session')->getFlashBag()->add('danger', 'Something went wrong. Please try again.');
			}
		}
		
		return $this->redirect($this->generateUrl('album'));
	}
}

src/CI/BandkadaBundle/Resources/views/Album/edit.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIBandkadaBundle:Album:macro.html.twig' as macro %}

{% block breadcrumbs %}
<li><a href="{{ path('album') }}">Albums</a></li>
<li><a href="{{ path('album_show', { 'id' : entity.id }) }}">{{ entity.name }}</a></li>
<li class="active">Edit</li>
{% endblock %}

{% block content %}
<div class="page-header">
	<h1>{{ FAIcon('picture-o', 'page-header-icon') }} {{ entity.name }}</h1>
</div>

{% if form_errors(edit_form) is not empty %}
	{{ form_errors(edit_form) }}<br/>
{% endif %}

{{ form_start(edit_form, {'action': path('album_update', { 'id' : entity.id }), 'method': 'PUT', 'attr': {'class': 'form-horizontal', 'novalidate' : 'novalidate' } }) }}
	<div class="row">
		{{ bootstrap_set_style('horizontal') }}
		<div class="col-sm-12">
			<div class="row">
				<div class="col-sm-5">
					{{ utils.imageThumbnail(edit_form,  entity.id ? entity.webPath : null, 1) }}
					{{ form_row(edit_form.name) }}
					{{ form_row(edit_form.eventDate) }}
				</div>
				
				<div class="col-sm-5">
					{{ form_row(edit_form.description) }}
				</div>
			</div>
			
			<br/>
			
			<div class="row">
				<div class="col-sm-12">
	        		<div class="table-responsive">
	        			<table class="table table-primary table-collection" data-prototype="{{ macro.media(edit_form.media.vars.prototype)|e }}">
							<thead>
								<tr>
									<th class="col-sm-5 text-center">Image <small>(required)</small></th>
									<th class="col-sm-6 text-center">Youtube Video Embed Code</th>
									<th class="col-sm-1"></th>
								</tr>
							</thead>
							<tbody>
								{% for key, media in edit_form.media %}
								<tr>
									{{ macro.media(media, key) }}
								</tr>
								{% endfor %}
							</tbody>
						</table>
						
						<btn class="btn btn-outline add-btn">{{ FAIcon('plus', 'btn-label') }} Add Media</btn>
	        		</div>
				</div>
			</div>
			
			<br/>
			
			<div class="row">
				<div class="col-sm-12">
					<div class="form-actions">
						{{ form_widget(edit_form.save) }}
						<a href="{{ path('album_show', { 'id' : entity.id }) }}" class="btn btn-default">Back</a>
					</div>
				</div>
			</div>
	    </div>
    </div>
    {{ form_widget(edit_form._token) }}
</form>
{% endblock %}

{% block javascripts %}
<script src="{{ asset('assets/js/album.js') }}"></script>
<script src="{{ asset('assets/js/file.js') }}"></script>
<script>
$(document).ready(function(){
	$( ".input-group.date" ).datepicker({
		changeMonth: true,
		changeYear: true,
		autoclose: true,
		todayHighlight: true
	});
});
</script>
{% endblock %}

src/CI/BandkadaBundle/Resources/views/Album/index.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIBandkadaBundle:Misc:macros.html.twig' as macros %}

{% block breadcrumbs %}
<li>Albums</li>
<li class="active">List</li>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>{{ FAIcon('picture-o', 'page-header-icon') }} Albums</h1>
			<div class="pull-right">
				<a class="btn btn-default btn-labeled btn-sm" href="{{ path('album_new') }}">{{ FAIcon('plus', 'btn-label') }} Add New</a>
				<a class="btn btn-default btn-labeled btn-sm" href="{{ path('album') }}">{{ FAIcon('th-large', 'btn-label') }} List All</a> 
			</div>
		</div>
		
		<!-- search form -->
		<div class="row search-filters">
			{{ form_start(search_form, {'action': path('album'), 'method': 'GET', 'attr': {'class': 'form-horizontal', 'novalidate' : 'novalidate' } }) }}
				{{ bootstrap_set_style('horizontal') }}
				<div class="col-md-5">
					{{ form_row(search_form.name) }}
					{{ form_row(search_form.search) }}
				</div>
				<div class="col-md-5">
					{{ form_row(search_form.dateFrom) }}
					{{ form_row(search_form.dateTo) }}
				</div>
			{{ form_end(search_form) }}
		</div>
		<!-- end of search form -->
		
		{% if pagination.getPaginationData['totalCount'] > 0 %}
			<div id="display-count" class="pull-right">
				{{ macros.paginationCount(pagination) }}
			</div>
			
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th class="col-md-1">Actions</th>
							<th class="col-md-3">{{ utils.sortableTableHeader(pagination, 'a.name', 'Name') }}</th>
							<th class="col-md-2">{{ utils.sortableTableHeader(pagination, 'a.eventDate', 'Event Date') }}</th>
							<th class="col-md-6">Description</th>
						</tr>
					</thead>
					<tbody>
						{% for entity in pagination %}
						<tr>
							<td class="actions">
								<div class="btn-group btn-group-sm">
									<button  type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#">{{ FAListIcon('cog') }}</button>
									<ul class="dropdown-menu">
										<li><a href="{{ path('album_show', {'id':entity.id}) }}">{{ FAListIcon('search-plus') }} View</a></li>
										<li><a href="{{ path('album_edit', { 'id': entity.id }) }}">{{ FAListIcon('pencil') }} Edit</a></li>
										<li class="divider"></li>
										<li><a href="{{ path('album_confirm_delete', { 'id': entity.id }) }}">{{ FAListIcon('trash-o') }} Delete</a></li>
									</ul>
								</div>
							</td>
							<td><a href="{{ path('album_show', { 'id' : entity.id }) }}">{{ entity.name }}</a></td>
							<td>{{ utils.formatDate(entity.eventDate) }}</td>
							<td>{{ entity.description|nl2br }}</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="pull-right">
				{{ knp_pagination_render(pagination) }}
			</div>	
		{% else %}
			<div class="alert">
				No results found.
			</div>
		{% endif %}
	</div>
</div>
{% endblock content %}

{% block javascripts %}
<script>
$(document).ready(function(){
	$( ".input-group.date" ).datepicker({
		changeMonth: true,
		changeYear: true,
		autoclose: true,
		todayHighlight: true
	});
});
</script>
{% endblock %}

src/CI/BandkadaBundle/Resources/views/Album/macro.html.twig
{% macro media(media, key) %}
{% import 'CICoreBundle::utils.html.twig' as utils %}

<tr{% if key is defined %} data-key="{{ key }}"{% endif %}>
	<td>
		{{ utils.imageThumbnail(media,  media.vars.value and media.vars.value.id ? media.vars.value.webPath : null, 0) }}
		{{ form_errors(media.file) }}
	</td>
	<td>{{ form_widget(media.youtubeVideoEmbedCode) }} {{ form_errors(media.youtubeVideoEmbedCode) }}</td>
	<td class="text-right">
		<p class="form-control-static"><a href="#" class="btn btn-default btn-sm delete-btn">{{ icon('trash') }}</a></p>
	</td>
</tr>
{% endmacro %}

src/CI/BandkadaBundle/Resources/views/Album/show.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}

{% block breadcrumbs %}
<li><a href="{{ path('album') }}">Albums</a></li>
<li class="active">View</li>
{% endblock breadcrumbs %}

{% block content %}
<div class="page-header">
	<div class="row">
		<div class="col-sm-7">
			<h1>{{ FAIcon('picture-o', 'page-header-icon') }} {{ entity.name }}</h1>
		</div>
		
		<div class="col-sm-5">
			<div class="pull-right btn-toolbar">
				<div class="btn-group btn-group-md">
					<a href="{{ path('album_edit', { 'id': entity.id }) }}" class="btn btn-default">{{ FAIcon('pencil') }} Edit</a>

					<div class="btn-group">
						<a href="#" class="btn dropdown-toggle" data-toggle="dropdown">More {{ FAIcon('caret-down') }}</a>
						<ul class="dropdown-menu">
							<li><a href="{{ path('album_confirm_delete', { 'id': entity.id }) }}">{{ FAIcon('trash-o') }} Delete</a></li>
						</ul>
					</div>
				</div>
				
				<div class="btn-group btn-group-md">
					<a class="btn btn-default" href="{{ path('album') }}">{{ FAIcon('th-large') }} List All</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-sm-12">
		<div class="row">
			<div class="col-md-5 col-xs-12">
				<table class="table table-no-border table-cascade profile">
					<tr>
						<th class="col-xs-4">Album Cover</th>
						<td><img src="{{ asset(entity.webPath) | imagine_filter('image_thumbnail') }}" /></td>
					</tr>
					<tr>
						<th>Name</th>
						<td>{{ entity.name }}</td>
					</tr>
					<tr>
						<th>Event Date</th>
						<td>{{ utils.formatDate(entity.eventDate) }}</td>
					</tr>
				</table>
			</div>
			
			<div class="col-md-6 col-xs-12">
				<table class="table table-no-border table-cascade profile">
					<tr>
						<th class="col-xs-4">Description</th>
						<td>{{ entity.description|nl2br }}</td>
					</tr>
				</table>
			</div>
		</div>
		
		<br/>
		
		<div class="row">
			<div class="col-md-12"> 
				<div class="table-responsive">
					<table class="table table-light">
						<thead>
							<tr>
								<th class="col-sm-4 text-center">Image</th>
								<th class="col-sm-8 text-center">Youtube Video Embed Code</th>
							</tr>
						</thead>
						<tbody>
							{% for media in entity.media %}
								<tr>
									<td>
										<div class="text-center">
											<img src="{{ asset(media.webPath) | imagine_filter('image_thumbnail') }}" />
										</div>
									</td>
									<td>
										<div class="text-center video-content">
											{{ media.youtubeVideoEmbedCode|raw }}
										</div>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
		
		{% include 'CIBandkadaBundle:Misc:entityDateDetails.html.twig' with {'entity': entity } %}
	</div>
</div>
{% endblock content %}